# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Mamba/project_mamba_all1/project_mamba_all1.srcs/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp.xci
# IP: The module: 'slim_WBUF_bank_dp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Mamba/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'slim_WBUF_bank_dp'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Mamba/project_mamba_all1/project_mamba_all1.srcs/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp.xci
# IP: The module: 'slim_WBUF_bank_dp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Mamba/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'slim_WBUF_bank_dp'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
