# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Mamba/project_mamba_all1/project_mamba_all1.srcs/sources_1/ip/s_buffer/s_buffer.xci
# IP: The module: 's_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Mamba/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/s_buffer/s_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 's_buffer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Mamba/project_mamba_all1/project_mamba_all1.srcs/sources_1/ip/s_buffer/s_buffer.xci
# IP: The module: 's_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Mamba/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/s_buffer/s_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 's_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
