@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Mar 16 13:58:58 +0100 2026
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab --incr --debug typical --relax --mt 2 -L xil_defaultlib -L blk_mem_gen_v8_4_8 -L fifo_generator_v13_2_10 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_reuse_top_mac_plus_bias_fifo_sigmoid_ew_gate_behav xil_defaultlib.tb_reuse_top_mac_plus_bias_fifo_sigmoid_ew_gate xil_defaultlib.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L xil_defaultlib -L blk_mem_gen_v8_4_8 -L fifo_generator_v13_2_10 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_reuse_top_mac_plus_bias_fifo_sigmoid_ew_gate_behav xil_defaultlib.tb_reuse_top_mac_plus_bias_fifo_sigmoid_ew_gate xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
